footballtalks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
    path("",include("schedule.urls")),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="main/password_reset.html"), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main/password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="main/password_reset_sent.html"), name='password_reset_done'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="main/password_reset_done.html"), name='password_reset_complete'),
    path("tinymce/",include("tinymce.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"),
    path("",include("schedule.urls")),
    path("register/", views.register,name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("about/", views.about, name="about"),
    path("change_password/", views.change_password, name="change_password"),
    path("upload/", views.upload_file, name="upload"),
    path("news/", views.news, name="news"),
    path('news/<str:slug>/', views.read_article, name="read_article"),
    
]

schedule/urls.py
from django.urls import path
from schedule import views

#TEMPLATE TAGGING
app_name = 'schedule'

urlpatterns = [
    path('matches/', views.get_match_data, name='match_data'),
    path('matches/<int:match_id>/', views.match_details, name='match_details'),   
]

main/models.py
from django.db import models
from tinymce.models import HTMLField
# Create your models here.

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

class BlogPost(models.Model):
    title = models.CharField(max_length=120, null=True, blank=False)
    subtitle = models.CharField(max_length=180, null=True, blank=False)
    slug = models.CharField(max_length=240, null=True, blank=False)
    image = models.FileField(upload_to='article_img/',null=True, blank=False)
    body = HTMLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from .models import Document


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)    
    class Meta:
        model = User
        fields = ("username", "email","first_name","last_name","password1", "password2")


    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields =  (
            'username',
            'email',
            'first_name',
            'last_name',
        )
        labels = {
            'username': _('Username'),
            'email': _('Email'),
            'first_name': _('First Name'),
            'last_name': _('Last Name')
        }

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', )

main/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import (
    AuthenticationForm,UserChangeForm, PasswordChangeForm
)
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from .forms import NewUserForm, EditProfileForm, DocumentForm
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from .models import  Document,BlogPost

def home(request):
    return render(request = request,
                  template_name='main/home.html',
                  context= {})

                  
def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("main:home")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(request = request,
                          template_name = "main/register.html",
                          context={"form":form})

    form = NewUserForm
    return render(request = request,
                  template_name = "main/register.html",
                  context={"form":form})

def logout_request(request):
    logout(request)
    # messages.info(request, "Berhasil Keluar Akun!")
    return redirect("main:login")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request,f"Anda masuk sebagai: {username}")
                return redirect("main:home")
            else:
                messages.error(request, "Username atau Kata Sandi Tidak Sesuai")
        else:
            messages.error(request, "Username atau Kata Sandi Tidak Sesuai")
    form = AuthenticationForm()
    return render(request, 
                    "main/login.html", 
                    {"form":form})

def profile(request):
    args = {"user": request.user}
    return render(request, "main/profile.html", args)

def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("main:profile")
    else:
        form = EditProfileForm(instance=request.user)
        args = {"form": form}
        return render(request,"main/edit_profile.html",args)


def about(request):
    return render(request = request,
                  template_name='main/about.html',
                  context = {})

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("main:profile")
        else:
            return redirect("main:change_password")
    else:
        form = PasswordChangeForm(user=request.user)
        args = {"form": form}
        return render(request,"main/change_password.html",args)

def upload_file(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = DocumentForm()
    return render(request, 'main/upload.html', {
        'form': form
    })
def news(request):
    qs = BlogPost.objects.all()
    return render(request = request,
                  template_name='main/news.html',
                  context= {'object_list': qs})


def read_article(request, slug):
    obj = get_object_or_404(BlogPost, slug=slug)
    return render(request, "main/read_article.html", context = {'object': obj})

templates/main/about.html
{% extends "main/base.html" %}

{% block content %}

About

{% endblock %}

templates/main/change_password.html
{% extends "main/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<h1 style="text-align:center">Ubah Kata Sandi</h1><br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div id="div_id_old_password" class="form-group"> <label for="id_old_password" class=" requiredField">
                Old Password<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="old_password" autocomplete="current-password" autofocus class="textinput textInput form-control" required id="id_old_password"> </div> </div> <div id="div_id_new_password1" class="form-group"> <label for="id_new_password1" class=" requiredField">
                New Password<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="new_password1" autocomplete="new-password" class="textinput textInput form-control" required id="id_new_password1"> <small id="hint_id_new_password1" class="form-text text-muted"><ul><li>Kata sandi anda tidak boleh mirip dengan informasi pribadi anda.</li><li>Kata sandi anda harus memiliki minimal 8 karakter.</li><li>Jangan menggunakan kata sandi yang sering digunakan.</li><li>Kata sandi anda tidak boleh hanya angka saja.</li></ul></small> </div> </div> <div id="div_id_new_password2" class="form-group"> <label for="id_new_password2" class=" requiredField">
                New Password Confirmation<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="new_password2" autocomplete="new-password" class="textinput textInput form-control" required id="id_new_password2"> </div> </div>
        <a href="/edit_profile"><strong>Change Profile</strong></a><br><br>
        <button type="submit" class="btn btn-primary"><strong>Change</strong></button> <br><br>
    </form>
</div>
{% endblock %}

templates/main/login.html
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
{% load crispy_forms_tags %}
{% block content %}

{% load static %}


<link rel="stylesheet" href="{% static 'main/login.css' %}">
<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
        <div class="card login-card" style="background-color:  #333131;">
            <div class="row no-gutters">
                <div class="col-md-6 d-flex justify-content-center align-items-center">
                <a href="/" >
                    <img src="{% static 'img/logo.png' %}" height="350" width="375">
                </a> 
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h4><strong class="text-white">LOGIN</strong></h4> 
                        <br> 
                        <form method="POST" class="text-white">
                            {% csrf_token %}
                            <div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
                              Username<span class="asteriskField"></span> </label> <div class=""> <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput form-control" required id="id_username"> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class=" requiredField">
                              Password<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required id="id_password"> </div> </div>
                            <button  type="submit" class="btn btn-primary " ><strong>Login</strong></button>
                        </form>
                        <span class="text-white">If you don't have an account, <a href="/register"><strong>Register</strong></a> first.</span>
                        <br>
                        <a href="/reset_password"><strong>Forgot Password</strong></a>
                        <br>
                        <br>
                    </div> 
                </div>    
            </div>
            
        </div>   
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/main/match-details.html
{% extends 'main/base.html' %}
<style>
	table tr td th {
    padding-left: 0;
    padding-right: 0;
}
</style>
{% block content %}
<div class="container" style="background-color: white;">
	
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-6">
			<div style="margin-top:20px" class="clearfix">
				<div style="float:left">
					<a href="/matches">{{match_info.league_name}}</a> {{match_info.match_date}}
				</div>
				<div style="float:right;">
					{{match_info.match_status}}
				</div>
			</div>
			<div class="clearfix" style="margin-top:10px">

				<div style="margin-left:55px;float:left">

					<img src="//ssl.gstatic.com/onebox/media/sports/logos/Id84F7Ji9rZGVacaazlBYA_96x96.png" alt="" style="width:48px;height:48px">
					<br></br>
					<span>{{match_info.match_hometeam_name | safe }}</span>


				</div>
				<div style="display:inline;margin-left:100px">
					<div style="font-size:40px;display:inline">{{match_info.match_hometeam_score}}</div>
					<div style="font-size:40px;margin-left:50px; margin-right:50px; display:inline">-</div>
					<div style="font-size:40px;display:inline">{{match_info.match_awayteam_score}}</div>
				</div>

				<div style="margin-right:55px;float:right">

					<img src="//ssl.gstatic.com/onebox/media/sports/logos/Tyy5rCdiLCw2_8z04DM-GQ_96x96.png" alt="" style="width:48px;height:48px"></img>
					<br></br>
					<span> {{match_info.match_awayteam_name | safe }}</span>

				</div>

			</div>

				<hr style="width:90%"></hr>

			<div>
				<div style="font-size:12px;color:#787878;float:left; margin-bottom:15px;">
					<ul style="list-style-type:none; display:inline">
						{% for scorer in goalscorer %}
							{% if scorer.home_scorer != ""  %}
							<li>{{scorer.home_scorer | safe }} {{scorer.time}}</li>
							{% endif %}
						{% endfor %}
					</ul>
				</div>

				<div style="display:inline; margin-left:30px">
					<img style="width:24; height:24; margin-top:15" src="//ssl.gstatic.com/onebox/sports/soccer_timeline/soccer-ball-retina.png" alt="Goals">
				</div>


				<div style="font-size:12px; color:#787878;float:right; margin-bottom:15px;">
					<ul style="list-style-type:none;display:inline">
						{% for scorer in goalscorer %}
							{% if scorer.away_scorer != "" %}
								<li>{{scorer.away_scorer | safe }} {{scorer.time}}</li>
							{% endif %}
						{% endfor %}
					</ul>
					
				</div>
			</div>
			<div>
			</div>

		</div>

		<div class="col-md-3">
		</div>

	</div>
</div>
<div class="container" style="margin-top:30;background-color:white">
	<div class="row">
		<div class="col-md-3"></div>

		<div class="col-md-6">

			<ul class="nav nav-tabs">
				<li><a class="nav-link" data-toggle="tab" href="#stats">STATS</a></li>

			</ul>

				<!-- Statistics -->
				<div id="stats" class="tab-pane fade">
					<table style="margin-left:50px" class="table table-borderless">
						<thead>
							<tr>
								<th scope="col">
								<img
								src="//ssl.gstatic.com/onebox/media/sports/logos/Id84F7Ji9rZGVacaazlBYA_48x48.png"
								alt=""
								style="width:24px;height:24px;">
								</th>
								<th scope="col" style="align-items: center;">STATS</th>
								<th scope="col">
								<img
								src="https://ssl.gstatic.com/onebox/media/sports/logos/Tyy5rCdiLCw2_8z04DM-GQ_48x48.png"
								alt=""
								style="width:24px;height:24px;">
								</img>
								</th>
							</tr>
						</thead>
						<tbody>
							{% if statistics %}
								{% for stats in statistics %}
									<tr>
										<td>{{stats.home}}</td>
										<td style="align-items: center;">{{stats.type}}</td>
										<td>{{stats.away}}</td>
								</tr>
								{% endfor %}
							{% endif %}
						</tbody>
					</table>
				</div>
				<!-- News will be available in future version -->
			<div id="news" class="tab-pane fade"></div>
			</div>
		</div>
		</div>

		<div class="col-md-3"></div>
	</div>
</div>
{% endblock %}

templates/main/match.html
{% extends 'main/base.html'%}

{% block content %}
			<form class="" action="{% url 'schedule:match_data' %}" method="POST">
				{% csrf_token %}
			<div class="container-fluid" style="background-color:white;width:80%"style="margin-top:50px;">
			<div class="row" style="margin-top: 30px;">
				<div class="col-md-1">
				</div>
				<div class="form-group col-md-3">
				<label style="margin-top:20px;" for="inputLeague"><strong>League</strong></label>
				<select name="league_id" class="form-control">
					<!-- {% for league in competitions %}
					<option value="{{league.league_id}}"> {{league.league_name}} </option>
					{% endfor %} -->
					<option value="148">English Premier League</option>
					<option value="149">Championship</option>
				</select>
				</div>

				<div class="form-group col-md-3">
					<label style="margin-top:20px;" for="inputFromDate"><strong>From Date</strong></label>
					<input type="date" name="from_date" class="form-control" id="inputFromDate" placeholder="10/2/2019"></input>
				</div>

				<div class="form-group col-md-3">
					<label style="margin-top:20px;" for="inputFromDate"><strong>To Date</strong> </label>
					<input type="date" name="to_date" class="form-control" id="inputToDate" placeholder="10/2/2019"></input>
				</div>

				<div class="form-group col-md-1" style="margin-top:32px">

					<input style="margin-top:20px;" type="submit" value="Show Matches" class="btn btn-primary">
				</div>
			</div>
			</form>

			<div class="row">
				<div class="col-md-3">
				</div>
				<div class="col-md-7">
					<table class="table table-hover">
						<tbody>
							{% if match_data %}
							{% for match in match_data %}
								<tr style="border:0 solid white;" class="table-row" data-href='{{match.match_id}}'>
									
						          <td>
						            <div>
						              <img src="//ssl.gstatic.com/onebox/media/sports/logos/Id84F7Ji9rZGVacaazlBYA_48x48.png" alt="" style="width:24;height:24" data-atf="1">
						              <span style="margin-left:15">{{match.home_team | safe }}</span>
						            </div>
						            <div style="margin-top:15">
						            <img src="https://ssl.gstatic.com/onebox/media/sports/logos/Tyy5rCdiLCw2_8z04DM-GQ_48x48.png" alt="" style="width:24;height:24"data-atf="1">
						              <span style="margin-left:15">{{match.away_team | safe }}</span>
						            </div>
						          </td>
						          <td>
						          <div>
						            {{match.home_team_score}}
						          </div>
						          <div style="margin-top:15">
						            {{match.away_team_score}}
						          </div>
						          </td>
						          <td>
									  <div class="vl">
													{% if match.match_status %}
													<!--  have to write code when game is live-->
													<div>
													{{match.match_status}}
													</div>
													<div>
					 							 	{{match.match_date}}
					 							 </div>
					 							 <div>
					 							 	{{match.match_time}}
					 							 </div>
													{% endif %}
								  </td>
								  
								</tr>
							{% endfor %}

							{% else %}
							 <p>{{match_error.message }} Please select another date range!</p>
							{% endif %}
						</tbody>
					</table>
				</div>
				<div class="col-md-3">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/main/news.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
  
{% for object in object_list %}
        <div class="container-fluid" style="width:40%;margin-top:50px;">
            <div class="mt-3">    
                <div class="card mb-3">
                    <div class="card-body">
                        <img class="card-img-top"src="{{ MEDIA_URL }}{{object.image}}" alt="Card image cap" width="200" height="450" >
                        <h5 class="card-title"><a href="{{object.slug}}">{{object.title}}</a></h5>
                        <p class="card-text">{{object.subtitle}}</p>
                        <p class="card-text"><small class="text-muted">Published: {{object.created_at}}</small></p>
                    </div>
                </div>
            </div>
        </div>    
    {% empty %}
        <p>Sorry, no articles have been written yet.</p>
    {% endfor %}
   
   
{% endblock %} 

templates/main/password_reset.html
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

{% load crispy_forms_tags %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'main/login.css' %}">
<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card" style="background-color:  #333131;">
        <div class="row no-gutters">
            <div class="col-md-6 d-flex justify-content-center align-items-center">
            <a href="/" >
                <img src="{% static 'main/logo.png' %}" height="350" width="375">
            </a> 
            </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h4><strong class="text-white">RESET PASSWORD</strong></h4> 
                        <br> 
                        <form method="POST" class="text-white">
                            {% csrf_token %}
                            <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                              Email<span class="asteriskField"></span> </label> <div class=""> <input type="email" name="email" autocomplete="email" maxlength="254" class="emailinput form-control" required id="id_email"> </div> </div>
                            <button  type="submit" class="btn btn-primary"><strong>RESET</strong></button>
                        </form>
                        <span class="text-white">If you don't have an account, <a href="/register"><strong>Register</strong></a> first.</span>
                        <br>
                        <a href="/login"><strong>Login</strong></a>
                        <br>
                        <br>
                    </div> 
                </div>    
            </div>
            
        </div>   
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/main/password_reset_done.html
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'main/login.css' %}">
<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card" style="background-color:  #333131;">
        <div class="row no-gutters">
            <div class="col-md-6 d-flex justify-content-center align-items-center">
            <a href="/" >
                <img src="{% static 'main/logo.png' %}" height="350" width="375">
            </a> 
            </div>
                <div class="col-md-6 ">
                    <div class="card-body">
                        <h4><strong class="text-white">RESET PASSWORD</strong></h4> 
                        <br> 
                        <p class="text-white">We already reset your password. <br>Try to login with your new password</p>
                        <br>
                        <a href="/login"><strong>Login</strong></a>
                        <br>
                        <br>
                    </div> 
                </div>    
            </div>
            
        </div>   
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/main/password_reset_sent.html
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

{% load crispy_forms_tags %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'main/login.css' %}">
<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card" style="background-color:  #333131;">
        <div class="row no-gutters">
            <div class="col-md-6 d-flex justify-content-center align-items-center">
            <a href="/" >
                <img src="{% static 'main/logo.png' %}" height="350" width="375">
            </a> 
            </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h4><strong class="text-white">RESET PASSWORD EMAIL SENT</strong></h4> 
                        <br> 
                            <p class="text-white">We already sent an email to you.</p>
                            <p class="text-white">If you didn't receive the email, please check if you already input your email correctly and check your spam folder. Thank You </p>
                        <br>
                        <br>
                    </div> 
                </div>    
            </div>
            
        </div>   
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}


<h3>Atur Ulang Kata Sandi Terkirim</h3>


<p>Kami telah mengirimkan email kepada Anda tentang petunjuk untuk membuat ulang kata sandi Anda, jika memang terdapat akun dengan email yang Anda masukkan. Anda akan segera menerimanya.</p>

<p>Jika Anda tidak menerima email dari kami, mohon untuk memastikan bahwa Anda telah memasukan alamat email yang telah Anda daftarkan dan cek folder spam Anda. Terima kasih.</p>

templates/main/register.html
{% load static %}
<link rel="stylesheet" href="{% static 'main/register.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% load crispy_forms_tags %}
<body class="form-v6">
	<div class="page-content">
		<div class="form-v6-content">
			<form class="form-detail text-white" method="post">
		<h2>REGISTRATION</h2>
		<a href="/" class="d-flex justify-content-center align-items-center" >
			<img src="{% static 'img/logo.png' %}" alt="logo_ft"  height="200" width="225">
		  </a><br>
		{% csrf_token %}
				<div id="div_id_username" class="form-group form-group-align"> <label for="id_username" class=" requiredField">
          Username </label> <div class=""> <input type="text" name="username" maxlength="150" autofocus class="textinput textInput form-control" required id="id_username"> <small id="hint_id_username" class="form-text text-white">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small> </div> </div> 
        <div id="div_id_email" class="form-group form-group-align"> <label for="id_email" class=" requiredField">
          Email </label> <div class=""> <input type="email" name="email" class="emailinput form-control" required id="id_email"> </div> </div> 
        <div id="div_id_first_name" class="form-group form-group-align"> <label for="id_first_name" class=" requiredField">
          First Name </label> <div class=""> <input type="text" name="first_name" maxlength="20" class="textinput textInput form-control" required id="id_first_name"> </div> </div> 
        <div id="div_id_last_name" class="form-group form-group-align"> <label for="id_last_name" class=" requiredField">
          Last Name</label> <div class=""> <input type="text" name="last_name" maxlength="20" class="textinput textInput form-control" required id="id_last_name"> </div> </div> 
        <div id="div_id_password1" class="form-group form-group-align"> <label for="id_password1" class=" requiredField">
          Password </label> <div class=""> <input type="password" name="password1" autocomplete="new-password" class="textinput textInput form-control" required id="id_password1"> <small id="hint_id_password1" class="form-text text-white"><ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></small> </div> </div> 
        <div id="div_id_password2" class="form-group form-group-align"> <label for="id_password2" class=" requiredField">
          Password Confirmation</label> <div class=""> <input type="password" name="password2" autocomplete="new-password" class="textinput textInput form-control" required id="id_password2"> <small id="hint_id_password2" class="form-text text-white">Enter the same password as before, for verification.</small> </div> </div> 
        <br><div style="position:absolute;left: 45%;"><button  type="submit" class="btn btn-primary"><strong>Submit</strong></button></div>
		<br><br><br>
        <span class="text-white" style="margin-left:70">If you already have an account, <a href="/login"><strong>Login</strong></a> instead.</span> <br>
			</form>
		</div>
	</div>
</body>